import {
  LayoutDashboard,
  UsersRound,
  Settings,
  HelpCircle,
  DollarSign,
  Smartphone,
  UserPlus,
} from "lucide-react";

export const SideNavItem = [
  {
    title: "Dashboard",
    href: "/clients",
    icon: LayoutDashboard,
    visible: ["superAdmin", "admin", "user"],
    variant: "default",
    submenu: false,
  },
  {
    title: "Users",
    href: "#",
    icon: UsersRound,
    variant: "ghost",
    visible: ["superAdmin", "admin"],
    label: "43",
    submenu: true,
    subMenuItems: [
      { title: "Users", href: "/clients/users" },
      { title: "Add", href: "/clients/users/add" },
      { title: "Active", href: "/users/active" },
      { title: "Inactive", href: "/users/inactive" },
    ],
  },
  {
    title: "Contacts",
    href: "#",
    icon: UserPlus,
    visible: ["superAdmin", "user"],
    submenu: true,
    label: "23",
    subMenuItems: [
      { title: "Contacts", href: "/clients/contacts/" },
      { title: "Add Contact", href: "/clients/contacts/add" },
      { title: "Groups", href: "/clients/contacts/groups" },
      { title: "Add Group", href: "/clients/contacts/groups/add" }, // Updated for uniqueness
      { title: "Import Contacts", href: "/clients/contacts/import" },
    ],
  },
  // {
  //   title: "Messages",
  //   href: "/messages",
  //   icon: MessageSquare,
  //   visible: ["superAdmin", "user"],
  //   submenu: true,
  //   label: "137",
  //   subMenuItems: [
  //     { title: "Inbox", href: "/messages/inbox", icon: MessageSquare },
  //     { title: "Sent", href: "/messages/sent", icon: MessageSquare },
  //     { title: "Drafts", href: "/messages/drafts", icon: MessageSquare },
  //     { title: "Trash", href: "/messages/trash", icon: MessageSquare },
  //     { title: "Compose", href: "/messages/compose", icon: MessageSquare },
  //     { title: "Templates", href: "/messages/templates", icon: MessageSquare },
  //   ],
  // },
  // {
  //   title: "Email",
  //   href: "/email",
  //   icon: Mail,
  //   visible: ["superAdmin", "admin", "user"],
  //   submenu: true,
  //   label: "56",
  //   subMenuItems: [
  //     { title: "Inbox", href: "/email/inbox" },
  //     { title: "Compose", href: "/email/compose" },
  //     { title: "Sent", href: "/email/sent" },
  //     { title: "Drafts", href: "/email/drafts" },
  //     { title: "Templates", href: "/email/templates" },
  //     { title: "Email Settings", href: "/email/settings" },
  //   ],
  // },
  {
    title: "SMS",
    href: "/sms",
    icon: Smartphone,
    visible: ["superAdmin", "user"],
    submenu: true,
    subMenuItems: [
      { title: "Send SMS", href: "/clients/sms/send" },
      { title: "SMS History", href: "/clients//sms/history" },
      { title: "SMS Templates", href: "/sms/templates" },
      { title: "SMS Settings", href: "/sms/settings" },
    ],
  },
  // {
  //   title: "WhatsApp",
  //   href: "/whatsapp",
  //   icon: MessageCircle,
  //   visible: ["superAdmin", "admin", "user"],
  //   submenu: true,
  //   subMenuItems: [
  //     { title: "Send Message", href: "/whatsapp/send" },
  //     { title: "Message History", href: "/whatsapp/history" },
  //     { title: "Templates", href: "/whatsapp/templates" },
  //     { title: "WhatsApp Settings", href: "/whatsapp/settings" },
  //     { title: "WhatsApp API", href: "/whatsapp/api" },
  //   ],
  // },
  // {
  //   title: "Campaigns",
  //   href: "/campaigns",
  //   icon: Briefcase,
  //   visible: ["superAdmin", "admin", "user"],
  //   submenu: true,
  //   subMenuItems: [
  //     { title: "Create Campaign", href: "/campaigns/create" },
  //     { title: "Campaign List", href: "/campaigns/list" },
  //     { title: "Campaign Templates", href: "/campaigns/templates" },
  //     { title: "Campaign Reports", href: "/campaigns/reports" },
  //     { title: "Campaign Settings", href: "/campaigns/settings" },
  //   ],
  // },
  {
    title: "Settings",
    href: "/settings",
    icon: Settings,
    visible: ["superAdmin", "admin", "user"],
    submenu: true,
    subMenuItems: [
      { title: "Account", href: "/settings/account" },
      { title: "Privacy", href: "/settings/privacy" },
      { title: "Security", href: "/settings/security" },
    ],
  },
  {
    title: "Plans",
    href: "/plans",
    icon: DollarSign,
    visible: ["superAdmin", "admin", "user"],
    submenu: true,
    subMenuItems: [
      { title: "Plans", href: "/plans" },
      { title: "Add Plan", href: "/plans/add" },
    ],
  },
  {
    title: "Help",
    href: "/help",
    icon: HelpCircle,
    submenu: false,
    visible: ["superAdmin", "admin", "user"],
  },
];
